### ISSUE TITLE
Error with GSE52666

### ISSUE THREAD

**Issue by KwatME** [guma44/GEOparse#16]
**GSE52666**

File already exist: using local version.
Parsing ../data/geo/GSE52666_family.soft.gz:
 - DATABASE : GeoMiame
 - SERIES : GSE52666
 - PLATFORM : GPL10999
 - SAMPLE : GSM1273835
 - SAMPLE : GSM1273836
 - SAMPLE : GSM1273837
 - SAMPLE : GSM1273838
 - SAMPLE : GSM1273839
 - SAMPLE : GSM1273840
 - SAMPLE : GSM1273841
 - SAMPLE : GSM1273842
 - SAMPLE : GSM1273843
 - SAMPLE : GSM1273844
 - SAMPLE : GSM1273845
 - SAMPLE : GSM1273846
 - SAMPLE : GSM1273847
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-15-439a1c2ce4db> in <module>()
      6 
      7     # Download and/or load GEO dataset
----> 8     gse = GEOparse.get_GEO(geo=id_, destdir=DIR_GEO)
      9 
     10     print('\tannotation.head(): {}'.format(gse.phenotype_data))

/home/k/Jumis/gist/tools/GEOparse/GEOparse/GEOparse.py in get_GEO(geo, filepath, destdir, how, annotate_gpl, geotype, include_data, silent)
     64         return parse_GSM(filepath)
     65     elif geotype.upper() == "GSE":
---> 66         return parse_GSE(filepath)
     67     elif geotype.upper() == 'GPL':
     68         return parse_GPL(filepath, silent=silent)

/home/k/Jumis/gist/tools/GEOparse/GEOparse/GEOparse.py in parse_GSE(filepath)
    518               gpls=gpls,
    519               gsms=gsms,
--> 520               database=database)
    521     return gse
    522 

/home/k/Jumis/gist/tools/GEOparse/GEOparse/GEOTypes.py in __init__(self, name, metadata, gpls, gsms, database)
    590 
    591         for gsm_name, gsm in iteritems(gsms):
--> 592             assert isinstance(gsm, GSM), "All GSMs should be of type GSM"
    593         for gpl_name, gpl in iteritems(gpls):
    594             assert isinstance(gpl, GPL), "All GPLs should be of type GPL"

AssertionError: All GSMs should be of type GSM

Could you take a look at this and let me know what the issue is?

Thanks,

**Comment by KwatME** [comment]
Thank you for the maintenance.

**Comment by guma44** [comment]
Can you provide more details eg. version of libraries or complete snippet of code that would reproduce this error. I cannot reproduce this error when I execute:
```
import GEOparse                                            
gse = GEOparse.get_GEO("GSE52666")
print('\tannotation.head(): {}'.format(gse.phenotype_data))
```

It loads and prints everything correctly.

**Comment by KwatME** [comment]
Worked for me. Strange and thanks anyways
