### ISSUE TITLE
get_GEO(... silent=True) is NOT silent

### ISSUE THREAD

**Issue by dtenenba** [guma44/GEOparse#19]
When I call `getGEO()` with `silent=True` I expect no output at all. But the result is identical to that obtained with `silent=False`. 

Even if I redirect `sys.stdout` and `sys.stderr` to files, I still see the same output. 

Is it possible to really silence the output of `getGEO`?

Python 3.5.2
GEOparse 0.1.10
macOS 10.12.4

**Comment by guma44** [comment]
Hi, 
I will look at this. The ideal solution would be to use logging module and I think I will try to make it happen.

**Comment by xguse** [comment]
What is the status of this?  I was thinking that adding the logging functionality might be a great solution. But in the mean time, would you be interested in PRs that fix the immediate issue?

**Comment by guma44** [comment]
Hey, I did not touch it yet. I can make a quick fix for the time being without logging.

**Comment by bgriffen** [comment]
Indeed I get the same problem of silent=True not doing anything.

**Comment by guma44** [comment]
I see I really have to take a look on this. For the silent option, I noticed I have to come back to the old download function and omit wgetter because there is no option to silence it out. This is a bit more work I expected and I focused on solving more urgent issues. However, I see this is quite urgent too.

**Comment by bgriffen** [comment]
It doesn't break functionality but it sure makes debugging code a big of a nightmare as the widow is 99% get_GEO stdout. :)

**Comment by xguse** [comment]
I think I saw that it is literally like a single function that needs to be changed. One where the silent var is set but the if test didn't get added or something. I will look again on Monday.

Gus

Sent from my mobile.  Please excuse any brevity, typos, and/or lack of nuance!


-------- Original Message --------

**Comment by guma44** [comment]
I pushed to the master changes that should solve this issue. I have to prepare release now. If you find something wrong please let me know.
