### ISSUE TITLE
no columns at GSE

### ISSUE THREAD

**Issue by antonkulaga** [guma44/GEOparse#20]
When I try 
```python
gse = GEOparse.get_GEO(geo="GSE69263", destdir="./")
gse.columns
```
I get:
```
gse.columns
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'GSE' object has no attribute 'columns'
```
while in the docs it is mentioned that columns is a standard GSE property

**Comment by guma44** [comment]
Hi,

GSE object has no columns attribute. It is a container for GSMs. You can access each GSM in GSE with:
```
gse.gsms
```

Anyway  the data is empty:
```
>>> print gse.gsms.values()[0].columns
Empty DataFrame
Columns: [description]
Index: []
```

**Comment by antonkulaga** [comment]
>GSE object has no columns attribute. 

In such case, you should fix the docs https://geoparse.readthedocs.io/en/latest/usage.html#gse-series as columns is mentioned there as standard GSE property.

**Comment by guma44** [comment]
Hey,
Indeed. The description is OK but the name is wrong. Thanks!
