### ISSUE TITLE
biopython requirement

### ISSUE THREAD

**Issue by antonkulaga** [guma44/GEOparse#21]
Looks like this lib uses module Bio from Entrez submodule Biopython, but I do not see Biopython in requirements file

**Comment by xguse** [comment]
It looks like that is mentioned in the Changelog:

```
0.1.8 (2016-11-02)
---------------------

Thanks to Tycho Bismeijer:

* Python 3 Compatibility
* Bio.Entrez dependency optional
```

**Comment by guma44** [comment]
Indeed, it is used only for downloading SRA. I will put it in the docs that this is clear.
