### ISSUE TITLE
In parse_GDS_columns(), unknown subset_types discarded

### ISSUE THREAD

**Issue by sumin** [guma44/GEOparse#23]
I have varying outcomes with which subset_types I encounter per parse. Although I have not encountered the ones encoded `set(['individual', 'disease_state'])`, I have had to make use of `set(['dose', 'agent', 'time', 'gender'])`.  So, in `parse_GDS_columns`, I modified the code to start out with an empty `subset_ids` and collected everything on the fly.

This turned out nicely as each subset_type was accounted for in each sample in the end, so in `GDS.columns` no rows were dropped during `GDS.__init__()`.

**Comment by guma44** [comment]
Hey, thanks for report. Can you give me an example or maybe make a pull request that we can discuss it further?
