### ISSUE TITLE
more meaningful error in gsm.download_supplementary_files

### ISSUE THREAD

**Issue by antonkulaga** [guma44/GEOparse#24]
Whenever I try to use it it downloads everything, but in the end tells me:
```
Converting to /home/antonkulaga/rna-seq/containers/geoparse/GSM1696283/Supp_GSM1696283_Transgenic_Control_L4_A/SRR2040662_*.fasta.gz
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/antonkulaga/rna-seq/containers/geoparse/env/lib/python3.5/site-packages/GEOparse/GEOTypes.py", line 352, in download_supplementary_files
    self.download_SRA(email, filetype=sra_filetype, directory=directory)
  File "/home/antonkulaga/rna-seq/containers/geoparse/env/lib/python3.5/site-packages/GEOparse/GEOTypes.py", line 463, in download_SRA
    if "command not found" in perr:
TypeError: a bytes-like object is required, not 'str'
```
Probably it tries to find some SRA tools in the path. So, it is better just to say that SRA tools are not in the PATH

**Comment by guma44** [comment]
What python version do you use?

**Comment by antonkulaga** [comment]
python 3.5

**Comment by guma44** [comment]
I am looking at it.

**Comment by guma44** [comment]
Probably you do not have SRAToolkit but this you might know.

**Comment by antonkulaga** [comment]
Yes, just saw that there's a problem with the path, but it would be nice to have some meaningful error telling about it, not cryptic "TypeError: a bytes-like object is required, not 'str'"

**Comment by guma44** [comment]
The check procedure is giving error here. One line below there is a meaning full error returned :). Here is the problem described: https://stackoverflow.com/questions/606191/convert-bytes-to-a-python-string. As subprocess.cummunicate returns bytes not string in python 3.5.

**Comment by guma44** [comment]
I corrected this error.

**Comment by antonkulaga** [comment]
is the fix already in master?

**Comment by guma44** [comment]
yes
