### ISSUE TITLE
email is optional 

### ISSUE THREAD

**Issue by antonkulaga** [guma44/GEOparse#25]
In gsm.download_supplementary_files email field looks optional (as email=None by default) but in reality, it crashes with "Exception: You have to provide valid e-mail", that means this field is in fact mandatory. I suggest to either make email mandatory or to make it really optional and allow downloading SRAs without email

**Comment by guma44** [comment]
E-mail indeed is optional. It is not obligatory to download SRA.

**Comment by guma44** [comment]
Maybe we could check for the e-mail if download_sra is set to True (default value)?

**Comment by guma44** [comment]
I have updated documentation to be more clear that the e-mail is not optional when the download_sra=True.
