### ISSUE TITLE
fastq-dump parameters are not optimal

### ISSUE THREAD

**Issue by antonkulaga** [guma44/GEOparse#26]
I run fastq-dump with the following parameters:
```bash
 /opt/sratoolkit/fastq-dump --skip-technical --gzip --readids --read-filter pass --dumpbase --split-files --clip ${file}
```
(at https://edwards.sdsu.edu/research/fastq-dump/ there are good explanations for need in some of them). While default geoparse has
```bash
cmd = "fastq-dump --split-files --gzip %s --outdir %s %s"
 ```
That creates some problems. For instance, if I do not have --readids and use paired sra, I get two files with ideas that are the same, that creates problem for downstream analysis. If I do not provide --skip-technical, then I get some technical Illumina reads that have nothing to do with biology ( like Application Read Forward -> Technical Read Forward <- Application Read Reverse - Technical Read Reverse. ) --read-filter pass allows to get read of multiple N-s in reads

**Comment by guma44** [comment]
Hey,
Thanks for this comments. For me it was working like that but I think your proposition is a valid improvement. I will implement it.

**Comment by guma44** [comment]
So my proposition is to add a "fastq_dump_options" argument to the download_SRA function. It would be in a form of a dictionary where a user could as long forms of arguments with corresponding values as a key: value pair. eg.

```
fastq_dump_options = {
     'split-files': None,
    'readids': None,
    'read-filter': 'pass',                                                                                                                                                                                                       
    'dumpbase': None
 }
```
If the value is not truthy the option would be passed without any value. Then anybody would be able to override these values.

**Comment by guma44** [comment]
Hey,
As there was no comment on this I implemented it in the way I said before.
