### ISSUE TITLE
BUG: cannot " GEOparse.get_GEO(filepath= path)" On windows

### ISSUE THREAD

**Issue by crazypigs** [guma44/GEOparse#30]
> `gse = GEOparse.get_GEO(filepath=DIR_PATH)`

> `ValueError: Unknown GEO type: E:\. Available types: GSM, GSE, GPL and GDS`

This error arises from the way windows directory file path works i.e. "\\" as opposed to linux "/"

In GEOparse.py on line 77 is the culprit :

> `    else:
>         if geotype is None:
>             geotype = filepath.split("/")[-1][:3] ------------this line  #77
> 
>     logger.info("Parsing %s: " % filepath)
>     if geotype.upper() == "GSM":
>         return parse_GSM(filepath)
>     elif geotype.upper() == "GSE":
>         return parse_GSE(filepath)
>     elif geotype.upper() == 'GPL':
>         return parse_GPL(filepath)
>     elif geotype.upper() == 'GDS':
>         return parse_GDS(filepath)
>     else:
>         raise ValueError(("Unknown GEO type: %s. Available types: GSM, GSE, "
>                           "GPL and GDS.") % geotype.upper())
> `

**Comment by guma44** [comment]
Hi,
Thanks. I think I know how to fix it. I will do that as soon as I can.

**Comment by guma44** [comment]
I prepared a hotfix release for the bug. I hop this will solve the problem.
