### ISSUE TITLE
use `pandas.read_csv` rather than `DataFrame.from_csv`

### ISSUE THREAD

**Issue by Miserlou** [guma44/GEOparse#45]
`from_csv` is deprecated, so creates a lot of deprecation warnings in the code. Additionally, `read_csv` is 46x to 490x faster than `from_csv`. There are small changes to the interface, described [here](https://stackoverflow.com/a/26495839).

**Comment by guma44** [comment]
Thanks a lot for pointing this. I will add this to the things to do for the next release.

**Comment by Miserlou** [comment]
Closed via #45
