### ISSUE TITLE
GEOparse.logger.set_verbosity doesn't work

### ISSUE THREAD

**Issue by Miserlou** [guma44/GEOparse#47]
The docs mention there is a 

`GEOparse.logger.set_verbosity('ERROR')`

however, this causes:
`
AttributeError: 'Logger' object has no attribute 'set_verbosity'
`

This can be side-stepped with:

```
import logging
GEOparse.logger.setLevel(logging.getLevelName("ERROR"))
```

**Comment by guma44** [comment]
Your right. The name is used twice :/.

**Comment by guma44** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [GEOparse.logger.set_verbosity doesn't work](https://trello.com/c/msl9IZrI/7-geoparseloggersetverbosity-doesnt-work)
