### ISSUE TITLE
Cut a New Release?

### ISSUE THREAD

**Issue by Miserlou** [guma44/GEOparse#48]
Now that you've got https://github.com/guma44/GEOparse/issues/45 sorted, it'd be great if you could publish an updated package version!

**Comment by Miserlou** [comment]
Any chance of a cutting a new release? We're going live with a product extremely soon and we'd prefer not to have to main our own fork. The timeout fixes are critical us as otherwise we can have hung processes which may affect the size of our elastic infrastructure. A new release would be massively useful for us.

**Comment by guma44** [comment]
Yes, I think I will do in in next few days. It takes too long as you noticed.
