### ISSUE TITLE
Illegal filenames and no filtering of user input from GEO to create the filenames

### ISSUE THREAD

**Issue by theselim** [guma44/GEOparse#5]
I'm assuming this was developed by highly UNIX users, and thus there are some missing substitutions for illegal filenames for Windows. Specifically in the GEOTypes.py file on line 403

I modified to the substitution to this for my own purposes: `re.sub(r'[\s\*\?\(\),\.\:\%\|\"\<\>]`

**Comment by guma44** [comment]
Thanks. This is a good point. I do not remember when I last time used windows. I will take a look a this.

**Comment by theselim** [comment]
Yay you fixed it! I fixed it for my application too. Thanks again this package was such a huge help for me.

**Comment by guma44** [comment]
It took a bit of time :)
