### ISSUE TITLE
Partially parsing of large GPL file

### ISSUE THREAD

**Issue by ttyskg** [guma44/GEOparse#53]
Hi,
I sometimes want to parse large GPL files (e.g., GPL570), but my PC does not work due to out of memory. So, I'd like to be able to parse the GPL file partially by specifying the GSM samples to parse from the GPL. If you agree with my idea, I will make a pull request for this feature.

Thanks

**Comment by guma44** [comment]
Hi, I was on holidays with limited access to net. Yes, this could be a good feature and if you would like to do it - that's even more awesome.

**Comment by ttyskg** [comment]
Hi,
Thank you for your reply despite you are on holidays. I will make a pull request for the feature soon.

Enjoy your vacation!
