### ISSUE TITLE
Check if GSE entry is public

### ISSUE THREAD

**Issue by adirot** [guma44/GEOparse#60]
I've had an FTP error when trying to get_gse for: "GSE122295"
And then I realized it is because it is still private.... 
Is there a way to know is a GSE is private?

**Comment by guma44** [comment]
Hey, good point. I will check it and produce meaningfull error message.

**Comment by adirot** [comment]
Thank you so much! love your code, it's very helpful

‫בתאריך יום ד׳, 18 בספט׳ 2019 ב-9:25 מאת ‪Rafal Gumienny‬‏ <‪
notifications@github.com‬‏>:‬
