### ISSUE TITLE
How can I get gsm-gpl relation in multi-gpls gse.

### ISSUE THREAD

**Issue by yong27** [guma44/GEOparse#7]
Thank you for great project. It is very convenient to me.

My interested dataset has multi-GPLs GSE. I want to find specific GPL's samples. But I can not find where the relations are.

In this case,

```
>>> gse = GEOparse.get_GEO("GSE6532", destdir='data/', 
            annotate_gpl=True, include_data=True, silent=True)
>>> print(gse.gpls)
{'GPL570': <PLATFORM: GPL570>,
 'GPL96': <PLATFORM: GPL96>,
 'GPL97': <PLATFORM: GPL97>}
>>> print(len(gse.gsms))
741
```

How can I filter GPL570's samples?

**Comment by guma44** [comment]
Hi,
Relations are stored in the metadata attribute called "platform_id" for each gsm. From there you can build a mapping eg.

```
import GEOparse
gse = GEOparse.get_GEO("GSE6532", destdir='.', annotate_gpl=True, include_data=True)
for gsm_name, gsm in gse.gsms.iteritems():
    print gsm_name, gsm.get_metadata_attribute("platform_id")

GSM151199 GPL97
GSM151198 GPL97
GSM151195 GPL97
...
GSM151342 GPL570
GSM151227 GPL97
GSM151339 GPL570
GSM151338 GPL570
```

Best

**Comment by yong27** [comment]
I didn't think that would be in metadata_attributes. 

Thank you for great project! 

Regards,
Hyungyong Kim
